### PR TITLE
Inclusion of tH, H->tautau in HiggsAnalysis-HiggsToTauTau

### PR DESCRIPTION
**Pull request by rmanzoni**
We've integrated the single top plus Higgs, Higgs to tau tau analysis in the common HTT package as a SM channel, th, with two categories, emt indexed as 0 and mmt indexed as 1.

The changes are transparent to the SM analysis, if run à la HIG-13-004, as the limit config files are untouched and tH is not run, nor included by default.
To run tH one has to specify the -c "th" option whenever needed.

Having tH as a SM channel can be questionable, in case please @ffrensch @rcl11 @ajgilbert let me know how to procede.

### CODE REVIEW

**Comment by ajgilbert** [comment]
Hi Riccardo, thanks for doing this - it's nice to have everything consolidated. Personally I have no problem with adding this as a SM channel. If you don't mind I would like to spend a little more time looking at the changes, but I didn't see any issues on a first look through.

**Comment by rmanzoni** [comment]
Hi Andrew,
sure, take the time is needed.
It is not urgent, I just wanted to, eventually, set tH on record.

**Comment by ajgilbert** [comment]
Hi Riccardo, sorry it took a long time to merge to this. For the future I also converted the setup to a CombineHarvester script here: https://github.com/cms-analysis/HiggsAnalysis-HiggsToTauTau/blob/master/CombineHarvester/CombineTools/scripts/setup-tH.py. You might want to check I got all the systematics correct, but otherwise it should produce identical datacards.

**Comment by rmanzoni** [comment]
Hi Andrew,
thanks for including tH.
I'll check the results from CombineHarvester soon.

**Pull request merged**
